export default [
    {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }, {
        description: "Blah Blah Blah",
        id: 5,
        institution: "UNILAG",
        name: "Computer Science",
        others: "",
        requirement: "5 Credits",
        ssce: "maths, english,physic",
        utme: "maths, english,physics,chemistry",
    }
]
